name: Helm Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Helm Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Copy for helm
      - name: Add some files
        run: |
          cp LICENSE charts/kestra/LICENSE
          cp README.md charts/kestra/README.md

      - uses: J12934/helm-gh-pages-action@v2.0.0
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          charts-folder: "charts"
          deploy-branch: gh-pages

